import type { ServiceArea } from "@/types/content";
import { alamedaCountyZips, contraCostaCountyZips } from "@/content/east-bay-zips";

export const serviceAreas: ServiceArea[] = [
  {
    slug: "plumber-san-leandro-ca",
    city: "San Leandro",
    state: "CA",
    zips: ["94577", "94578", "94579"],
    intro:
      "Z and Z Plumbing is headquartered in San Leandro. We know the neighborhoods, the housing stock, and the older cast-iron and galvanized systems that need attention.",
    neighborhoods: ["Bay-O-Vista", "Estudillo Estates", "Washington Manor", "Davis", "Broadmoor"],
    isHQ: true,
  },
  {
    slug: "plumber-oakland-ca",
    city: "Oakland",
    state: "CA",
    zips: [
      "94601",
      "94602",
      "94603",
      "94604",
      "94605",
      "94606",
      "94607",
      "94608",
      "94609",
      "94610",
      "94611",
      "94612",
      "94613",
      "94614",
      "94615",
      "94617",
      "94618",
      "94619",
      "94621",
      "94622",
      "94623",
      "94624",
      "94649",
      "94659",
      "94660",
      "94661",
      "94666",
    ],
    intro:
      "Oakland is our largest service market. We run calls across all Oakland neighborhoods daily. Residential, commercial, and street-side lateral work.",
    neighborhoods: ["Fruitvale", "Temescal", "Rockridge", "Montclair", "Grand Lake", "West Oakland", "East Oakland"],
    isHQ: false,
  },
  {
    slug: "plumber-berkeley-ca",
    city: "Berkeley",
    state: "CA",
    zips: [
      "94701",
      "94702",
      "94703",
      "94704",
      "94705",
      "94707",
      "94708",
      "94709",
      "94710",
      "94712",
      "94720",
    ],
    intro:
      "Berkeley's older housing stock, bungalows from the 1920s and 1940s, often needs the kind of repipe and sewer lateral work we specialize in.",
    neighborhoods: ["Elmwood", "Claremont", "North Berkeley", "West Berkeley", "Southside"],
    isHQ: false,
  },
  {
    slug: "plumber-alameda-ca",
    city: "Alameda",
    state: "CA",
    zips: ["94501", "94502"],
    intro:
      "Alameda Island homes date back to the early 1900s. We serve the whole island for drain cleaning, sewer lateral, water heater, and repipe.",
    neighborhoods: ["Gold Coast", "West End", "Fernside", "Bay Farm Island"],
    isHQ: false,
  },
  {
    slug: "plumber-hayward-ca",
    city: "Hayward",
    state: "CA",
    zips: ["94540", "94541", "94542", "94543", "94544", "94545", "94557"],
    intro:
      "We serve Hayward residential and light commercial. Fast response from our San Leandro base, typically 30 to 60 minutes.",
    neighborhoods: ["Downtown Hayward", "Fairway Park", "Mission Hills", "Southgate"],
    isHQ: false,
  },
  {
    slug: "plumber-union-city-ca",
    city: "Union City",
    state: "CA",
    zips: ["94587"],
    intro:
      "Union City sits directly in our south East Bay service corridor. We run plumbing calls for homes and light commercial properties near Decoto, Alvarado, Union Landing, and the I-880 corridor.",
    neighborhoods: ["Decoto", "Alvarado", "Union Landing", "Seven Hills"],
    isHQ: false,
  },
  {
    slug: "plumber-fremont-ca",
    city: "Fremont",
    state: "CA",
    zips: ["94536", "94537", "94538", "94539", "94555"],
    intro:
      "We serve Fremont for sewer lateral, drain cleaning, water heater, repipe, and emergency plumbing calls from Centerville and Niles to Irvington, Mission San Jose, and Warm Springs.",
    neighborhoods: ["Centerville", "Niles", "Irvington", "Mission San Jose", "Warm Springs"],
    isHQ: false,
  },
  {
    slug: "plumber-newark-ca",
    city: "Newark",
    state: "CA",
    zips: ["94560"],
    intro:
      "Newark homes and businesses are inside our south East Bay response area. We cover drain cleaning, sewer work, repipes, water heaters, and emergency service across the city.",
    neighborhoods: ["Old Town Newark", "Dumbarton", "NewPark", "Lakeshore"],
    isHQ: false,
  },
  {
    slug: "plumber-castro-valley-ca",
    city: "Castro Valley",
    state: "CA",
    zips: ["94546", "94552"],
    intro:
      "Castro Valley hillside homes see a lot of root intrusion in their sewer lines. We run camera inspections, hydrojetting, and lateral work across the full Castro Valley ZIP area.",
    neighborhoods: ["Five Canyons", "Proctor", "Lake Chabot", "Palomares Hills"],
    isHQ: false,
  },
  {
    slug: "plumber-dublin-ca",
    city: "Dublin",
    state: "CA",
    zips: ["94568"],
    intro:
      "Dublin is part of the I-580 to I-680 corridor we cover between Castro Valley and Walnut Creek. We handle same-day plumbing calls, water heaters, drains, sewer lines, and repipes.",
    neighborhoods: ["West Dublin", "Dublin Ranch", "Downtown Dublin", "Tassajara"],
    isHQ: false,
  },
  {
    slug: "plumber-pleasanton-ca",
    city: "Pleasanton",
    state: "CA",
    zips: ["94566", "94588"],
    intro:
      "Pleasanton is inside our expanded East Bay service corridor. We serve homes and light commercial properties for sewer, drain, water heater, repipe, and emergency plumbing work.",
    neighborhoods: ["Downtown Pleasanton", "Stoneridge", "Val Vista", "Birdland"],
    isHQ: false,
  },
  {
    slug: "plumber-richmond-ca",
    city: "Richmond",
    state: "CA",
    zips: ["94801", "94802", "94804", "94805", "94807", "94808", "94850"],
    intro:
      "Z and Z serves Richmond for drain cleaning, sewer lateral, gas line, and water heater work. We cover the whole city.",
    neighborhoods: ["Point Richmond", "Iron Triangle", "Hilltop", "Annex"],
    isHQ: false,
  },
  {
    slug: "plumber-emeryville-ca",
    city: "Emeryville",
    state: "CA",
    zips: ["94608", "94662"],
    intro:
      "Emeryville commercial and residential clients call us for fast, licensed plumbing service. We're usually on-site within the hour.",
    neighborhoods: ["Bay Street", "Watergate", "Christie Park"],
    isHQ: false,
  },
  {
    slug: "plumber-pinole-ca",
    city: "Pinole",
    state: "CA",
    zips: ["94564"],
    intro:
      "We service Pinole for residential plumbing. Drain cleaning, water heaters, repipe, and sewer work.",
    neighborhoods: ["Old Town Pinole", "Giant Road", "Hercules border"],
    isHQ: false,
  },
  {
    slug: "plumber-lafayette-ca",
    city: "Lafayette",
    state: "CA",
    zips: ["94549"],
    intro:
      "Lafayette homeowners call us for sewer lateral inspections and repipe work. We handle larger residential projects across Contra Costa.",
    neighborhoods: ["Burton Valley", "Happy Valley", "Reliez Valley"],
    isHQ: false,
  },
  {
    slug: "plumber-walnut-creek-ca",
    city: "Walnut Creek",
    state: "CA",
    zips: ["94595", "94596", "94597", "94598"],
    intro:
      "Walnut Creek is now part of our regular East Bay service corridor. We handle sewer, drain, water heater, repipe, and emergency plumbing work from Rossmoor to Northgate.",
    neighborhoods: ["Downtown Walnut Creek", "Rossmoor", "Saranap", "Northgate", "Larkey Park"],
    isHQ: false,
  },
  {
    slug: "plumber-alameda-county-ca",
    city: "Alameda County",
    state: "CA",
    zips: [...alamedaCountyZips],
    intro:
      "Z and Z covers Alameda County from the inner East Bay through the Tri-Valley corridor. If your ZIP is in Alameda County and not listed under a specific city page, the request still routes as in-area.",
    neighborhoods: ["Oakland", "Berkeley", "Fremont", "Livermore", "Albany", "San Lorenzo"],
    isHQ: false,
  },
  {
    slug: "plumber-contra-costa-county-ca",
    city: "Contra Costa County",
    state: "CA",
    zips: [...contraCostaCountyZips],
    intro:
      "For larger projects and qualified calls, Z and Z covers Contra Costa County, including the I-680 corridor from San Ramon and Danville up through Alamo and Walnut Creek.",
    neighborhoods: ["Walnut Creek", "Alamo", "Danville", "San Ramon", "Lamorinda"],
    isHQ: false,
  },
];
